#+title: Automagically fill PDF forms
#+author: Thomas Rometsch

A commandline utility to fill a pdf form with information given in a textfile.
For recurring paperwork this can be a huge time saver, especially if the forms contain redundant information.

* Getting started

0) Install dependencies via =pip install --user pymupdf pdfrw=.
1) Run =./fill.py --enumerate {your form}.pdf= to produce a copy of the form in which an integer id is entered in to all text fields and checkboxes of the form.
2) Open ={your form}_numbered.pdf= for a reference of the available fields and their ids.
3) Make text file in which you specify your data like in the example below.
4) Finally run =./fill.py --input {your input textfile} {your form}.pdf= to produce the filled form with a default filename ={your form}_filled.pdf=. Adjust the filename with the =--outfile= option.
#+begin_example
# you can indicate comments with a '#' character

# you can also leave lines empty
# Now we input data with the syntax:
# {name to remember (not used)}     {field id}    {value .... (rest of the line also including whitespaces)}
FirstField         1     some data
SomeOtherField     42    2.8e7
#+end_example
Each non-comment and non-empty line is split in three parts.
The first part is a user defined name for the field, the second part is the interger id of the field and the third part is the value entered into the field. If third part is left empty, nothing is entered and the line is ignored.
For checkboxes, any value different than 0 causes the box to be checked.
